name: merge-validate

on: 
  pull_request:
    branches:
      - livekit

jobs:
  docker:
    name: merge-validate
    runs-on: ubuntu-latest
    steps:
      - name: Get the Ref
        id: get-ref
        uses: ankitvgupta/ref-to-tag-action@master
        with:
          ref: ${{ github.ref }}
          head_ref: ${{ github.head_ref }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: jq422pa7.gra7.container-registry.ovh.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jq422pa7.gra7.container-registry.ovh.net/magnify/staging:${{ steps.get-ref.outputs.tag }}
