name: production-build

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'livekit'
  push:
    branches:
      - 'livekit'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: jq422pa7.gra7.container-registry.ovh.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jq422pa7.gra7.container-registry.ovh.net/magnify/production:latest